apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:mIWwKNpe1sdfU2Y02tN2i8CYxjD7R+WWYQ2X,iv:aO1QGKiWhFKxra271nDXvFp4WKRaBtoFDOIpJQJpcgg=,tag:Nuznpl1bgFeUJFgFCMBd0Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:LVcQ5qg3NJHSOuoZEIFIDPV3Dz+W9FHsQ3yeQ3CEVVTW4i/fRQ==,iv:v7lcnofoUdVxDpTC785eL3qUpHu5u0AmQwPxALQYhSE=,tag:V/0bosWGxP2fnRRMtNfbfA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:AZTqBrbHAXn4F4DUvjz0glVNsUQjJQ==,iv:BgBxwSYHDPlV0rQtAz6AgjMjnDornN46h5pRtAf4bxE=,tag:70x4GiQvPX1kRwm0BhnBNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ymvemmd9aw4jf9k0kfu2ayaxuhtcp44lw9ggl84kjzm4cvdf2y9sdlfpm4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoS091eThYZXpFV0l5c3Ro
            Y3pXb1hFTDdLWkJ3bitTR2RORDFIVUlhUlE0Cmcyc0hOU0Q2RkJuK2EySDdJQ3Np
            Y2JRc2lTYmk3YllBS3c1QjZVVWRyZEkKLS0tIEwybWVJR2hhbHJqWXhab2g1SkVR
            T3lXWU05bjZlb3BRekZHOW1ZRFpZK0kKiXi80mQw2mJFM/2C81KJ6KXXxboG7ZWx
            UyHDjW3tWh2y7reQc6ZcxQS7Pxj0fRACDMIuF/HrjSc7G4X+szw75w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-21T18:02:18Z"
    mac: ENC[AES256_GCM,data:dwvHA4F48ejZt+eajmy+oDQhtYW5+nYE4wPL5y4B99EWIr0IH+qyry5PjqgPa1oiCh0iIbMHKBrtpGgNJMx6MYPPvvKaM2Ndli6YtP106zn4kH8bnCdxbZO+sDjXGYxd4RV3FMO+WcO+pphFjODdKB6hJ4DMNYhBHJDOvODu7D8=,iv:sL+0BHyU/1JUMKsRtuQGOfVPOqnIDkaWpwBf+Q1o82w=,tag:9AeIcWl7TQ6CMRIRIM0AzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
