apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:wJReFmXWQsf2jfmA+crm0YDDrVaq1KIeGaQd,iv:UuM39efi1hZJfGtoch4EibjQgPhTiUP2LILTUOBwAy4=,tag:SrY9LxchKepw8lFsoScuBw==,type:str]
    api-key: ENC[AES256_GCM,data:VWPzj3xG+Yz/1TSStrOcIfh2YauYGYfzC/IybDe0AdLxhgaeMw==,iv:S4BAiQUnF23zwggM5KMY90+sV71VovTH1SY8YhpxV7Q=,tag:g00/dyvLytUKwR1sWvJbgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ymvemmd9aw4jf9k0kfu2ayaxuhtcp44lw9ggl84kjzm4cvdf2y9sdlfpm4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRkgveVZsTTEwS2lyTEF3
            U1oyODhRSlhMVXNGWExZNVlZYUwybU1tSkZJCnRmaHhmcmV1eFNWYklSSXo4bGJu
            UmNSTU1FWHIrbDk1OXVHcWw4c3lITDgKLS0tIHdaNkdtcmRUNk5ncC9Sb0VUNlVy
            Qk93MG0vdnNpMHRESjBBc0hyS0xVd0UKr01XFIzjTwOOlifYBSujvjBh0bVL6bF3
            VghETHSN6EJTAanXigHfPYfTqCgpRrzqqezOCGA8F/+jbFflNjQMaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-21T23:49:31Z"
    mac: ENC[AES256_GCM,data:tuuo+xQguyFl5vUITuG3CQZ5IoZIXouNXscaoAXfdv8+n4Gm5DAH5qeksG5r5AcYHwWwkcjM0/9MW+UccKcqq4d7L8xXQ2/qHFqAy0OPusxKXqOc89smT2TYQFl1VD63tg69Lqv50rzHy7A6XdRU5Z1RPp3HyBIUsqm79eMDdzY=,iv:XFvTo6Iq8euuRtwIwYrmyMKctTZB8YNwcxwONyxgZ0A=,tag:tPIvjKBr/f32WE+No2MneA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
