apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:gZs+Ku+USagrW1pfa7uEKG3i2PQKbcKIzmt6,iv:tCnZ4krjwzbxZASyRneWDR/rZZ16PjcTQqs1wwmA5Gw=,tag:HH+v/XQEePnkYJYcWuWYgA==,type:str]
    api-key: ENC[AES256_GCM,data:aPvZqU0JGcgd44MavgFyg+aZCxB5IgXIKztQkKvAXs/TFE8+iQ==,iv:Hf93QDRQD7WyA4BcMP4ks5Wt0j9QajqC9Tu9rTzeD04=,tag:v96vBKP1Kxx49YHrKICbSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ymvemmd9aw4jf9k0kfu2ayaxuhtcp44lw9ggl84kjzm4cvdf2y9sdlfpm4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MkIyWTZoNzEyOStaaUla
            YThWSlRIOVpIMzlpVHhRTHVISTZFelpuNVVJCjFYMkhEM2c4ck5JeFhtaGkzcm9L
            dDRiKzcwWTdBVDQ2MlJGUmZ4ZksxSUUKLS0tIHdDMXYyNEZGWWVwSlF1ZjJza0tH
            OXBoUkxkMkNTL0lwajJLaVpYZS8vQWMKZlPbb9lIPtpFR5AgEuLTPKHotZW2W/tl
            YHmyi1GzLQ/+rvj7UA2LjvO/pAydS/s75kU6JiGytHpVr2RmFP77Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-21T18:02:18Z"
    mac: ENC[AES256_GCM,data:YdOob7efRnn5rDPeDoRpTGZxa6C+HLGqMxkX8KxthzJPDmit4fTzTKs5qcI6+YddA2fG56KcrNMhCZN5G4a9p3NYhja23MGHB+gcsSn0DhPN79zhnOt9RJ9QijB0GHosY1TzMh0bq/zEtsqQTD/RmCN+aSLxpOjU/5FymPTirZg=,iv:THbbAaYDeuzT3z6+x96FuBG9uLr6SwgpUcoV515JNQQ=,tag:SR73iWNgN2Va2bFnMmzOnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
