---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./echo-server/ks.yaml
  - ./hajimari/ks.yaml
  - ./octoprint/ks.yaml
  - ./openebs/ks.yaml
  - ./tautulli/ks.yaml
  - ./wordpress/ks.yaml
