---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octoprint-config-v1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: openebs-jiva-csi-default
